version: "3.8"
services:
  backend:
    image: "hami0334/springboot-react-fullstack:29.6.2021.10.41.19"
    ports: 
      - "80:8080"   # the - represents an element in an array
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    